### ISSUE TITLE
OCAT + Vulkan validation layer = stack overflow

### ISSUE THREAD

**Issue by Reedbeta** [GPUOpen-Tools/OCAT#33]
A Vulkan app I'm developing often experiences a stack overflow inside `vkCreateDevice` if launched with OCAT running, and the `LUNARG_standard_validation` layer enabled. Without the validation layer it works fine; also works fine with the validation layer but without OCAT.

The callstack looks like this:

 	nvoglv64.dll!000000005d60c9dd()	Unknown
 	nvoglv64.dll!000000005de6f6ab()	Unknown
 	nvoglv64.dll!000000005de7043d()	Unknown
 	vulkan-1.dll!00007ff9611cf605()	Unknown
 	vulkan-1.dll!00007ff9611cf605()	Unknown
 	vulkan-1.dll!00007ff9611cf605()	Unknown
 	vulkan-1.dll!00007ff9611cf605()	Unknown
 	...vulkan-1.dll!00007ff9611cf605() repeats indefinitely...

However, _sometimes_ it gets into a different "mode" where instead of producing a stack overflow, I'll get the following error message reported through the Vulkan debug callback: 

    Failed to open dynamic library "C:\Program Files (x86)\OCAT\Bin\.\VK_LAYER_OCAT_overlay32.dll" with error 193

And then everything works fine after that, including the OCAT overlay. This is a 64-bit app, so I'm not sure why it's trying to load the 32-bit OCAT overlay DLL.

OCAT 1.1.0.60, 64-bit Windows 10, fall creators update (version 1709), Geforce 970M with latest drivers (390.77), Vulkan SDK 1.0.65.1.

**Comment by aurolou** [comment]
Could you please try out e.g. this [version](https://ci.appveyor.com/api/buildjobs/bk0st7y0wbaao63a/artifacts/OCAT_1.1.0.112.exe)? With 1.1.0.68 we changed the Vulkan layer loading for the global hook.

I will have a look into the error when both, the OCAT and the validation layers, are enabled. Thanks for reporting the issue.

**Comment by Reedbeta** [comment]
Hi, with 1.1.0.112 I no longer see the stack overflow. However I now get another error reported by the VK debug callback:

    vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain

I have `oldSwapchain` set to null since I'm creating the swap chain for the first time. If I ignore this I get a cascade of other Vulkan errors about image formats and suchlike, and the app explodes. 😢

That's what happens with the validation layer on. Without it, I get a null pointer exception inside `vkQueuePresentKHR`, callstack inside nvoglv64.dll and VK_LAYER_OCAT_overlay64.dll.

**Comment by aurolou** [comment]
Hi, thanks for the update. I see if I can reproduce the issue.

All Vulkan applications I tried so far ran without problems though.

**Comment by Reedbeta** [comment]
More detail about the Vulkan errors I get using OCAT 1.1.0.112 with the validation layer (added OCAT log messages as well for context):

	OCAT: 02/13/18 14:33:10	INFO        VulkanOverlay 8480 VkRender.exe - MessageLog - Logging started
	OCAT: 02/13/18 14:33:10	INFO        VulkanOverlay 8480 VkRender.exe - Config - file loaded
	OCAT: 02/13/18 14:33:10	INFO        VulkanOverlay 8480 VkRender.exe - OverlayThread - Start overlay thread 
	vkCreateSwapChainKHR(): surface has an existing swapchain other than oldSwapchain
	vkCreateSwapchainKHR: internal drawable creation failed
	[inside vkGetSwapchainImagesKHR] vkCreateImageView() pCreateInfo->format VK_FORMAT_B8G8R8A8_SRGB cannot be used with an image having the VK_IMAGE_TILING_OPTIMAL and VK_IMAGE_USAGE_STORAGE_BIT flags set
	OCAT: 02/13/18 14:38:28	INFO        VulkanOverlay 8480 ImmersionVkRender.exe - VulkanOverlay - Create command pool
	[inside vkQueuePresentKHR] Attempt to free command buffer (0x000001C890797A18) which is in use

B8G8R8A8 is the only allowed swap chain format reported by `vkGetPhysicalDeviceSurfaceFormatsKHR`, at least on all of my machines (which are all NVIDIA GPUs, in case that's relevant). Whatever OCAT is doing behind the scenes doesn't seem to like that format much.

**Comment by aurolou** [comment]
Thanks for the output log, it helped a lot!
I pushed some changes, could you please check if this solves the issue for you?

**Comment by Reedbeta** [comment]
Thanks, I've tried 1.1.0.114. The app and overlay now work!

I'm still getting the following errors reported from the VK debug callback, though if I ignore them things do continue to work normally afterward:

    [inside vkGetSwapchainImagesKHR] vkCreateImageView() pCreateInfo->format VK_FORMAT_B8G8R8A8_SRGB cannot be used with an image having the VK_IMAGE_TILING_OPTIMAL and VK_IMAGE_USAGE_STORAGE_BIT flags set (4 times)
    [inside vkDestroyDevice] OBJ ERROR : For device 0x1c1d5694280, DeviceMemory object 0x14 has not been destroyed
    [inside vkDestroyDevice] OBJ ERROR : For device 0x1c1d5694280, Buffer object 0x13 has not been destroyed

**Comment by aurolou** [comment]
Hi,

sorry for the delay. I pushed some fixes which should hopefully solve the validation layer warnings. You can check this [version](https://ci.appveyor.com/api/buildjobs/kiyhlrkdmm56sbc7/artifacts/OCAT_1.1.0.119.exe). Thanks again for the report! :)

**Comment by Reedbeta** [comment]
Thanks! Just got around to testing this. Now I don't have any validation layer warnings when starting up through Visual Studio.

Oddly, though, I get this error coming through the debug callback, only when starting the app standalone, but not when launching through Visual Studio:

![image](https://user-images.githubusercontent.com/1578730/37302641-54249b84-25e9-11e8-9799-fcc3fece321d.png)

**Comment by rys** [comment]
Hey @Reedbeta, are you still having this issue? Just doing an OCAT issue review to close out any old stuff that's fixed in the most recent releases. Let us know if we need to keep this one open.

**Comment by Reedbeta** [comment]
Hi @rys, unfortunately with OCAT 1.3.0.189 the stack overflow issue has returned. Same symptoms as in the original post on this issue. With the validation layer enabled, I see a stack overflow inside `vkCreateDevice()` every time I launch my app.

Also, when running my app _without_ the validation layer, I get no overlay. No errors or anything apparently going wrong, just no OCAT overlay. However, the overlay _does_ appear when running `cube.exe` from the Vulkan SDK. I do get OCAT messages in my debug output (below), so it seems OCAT is attaching to the app; no idea why it's not putting up the overlay. This happens whether launching from Visual Studio or standalone.

	OCAT: 12/17/18 15:59:24	INFO        2116 VkRenderTest.exe - FileDirectory - Bin\	C:\Program Files (x86)\OCAT\Bin\
	OCAT: 12/17/18 15:59:24	INFO        2116 VkRenderTest.exe - FileDirectory - OCAT\	C:\Users\Reedbeta\Documents\OCAT\
	OCAT: 12/17/18 15:59:24	INFO        2116 VkRenderTest.exe - FileDirectory - Logs\	C:\Users\Reedbeta\Documents\OCAT\Logs\
	OCAT: 12/17/18 15:59:24	INFO        2116 VkRenderTest.exe - FileDirectory - Config\	C:\Users\Reedbeta\Documents\OCAT\Config\
	OCAT: 12/17/18 15:59:24	INFO        2116 VkRenderTest.exe - FileDirectory - Captures\	C:\Users\Reedbeta\Documents\OCAT\Captures\
	OCAT: 12/17/18 15:59:24	INFO        2116 VkRenderTest.exe - BlackList - Blacklist file loaded
	OCAT: 12/17/18 15:59:24	INFO        2116 VkRenderTest.exe - BlackList - Blacklist file loaded
	OCAT: 12/17/18 15:59:24	INFO        Version 1.3.0.189      GameOverlay64 2116 VkRenderTest.exe - MessageLog - Logging started
	OCAT: 12/17/18 15:59:24	INFO        Version 1.3.0.189      GameOverlay64 2116 VkRenderTest.exe - GameOverlay - Install process hooks for Vulkan
	OCAT: 12/17/18 15:59:24	INFO        Version 1.3.0.189      GameOverlay64 2116 VkRenderTest.exe - Hook Manager - Install hooks for CreateProcess
	OCAT: 12/17/18 15:59:24	INFO        Version 1.3.0.189      GameOverlay64 2116 VkRenderTest.exe - Hook Manager - Successfully installed hook for CreateProcessA
	OCAT: 12/17/18 15:59:24	INFO        Version 1.3.0.189      GameOverlay64 2116 VkRenderTest.exe - Hook Manager - Successfully installed hook for CreateProcessW
	OCAT: 12/17/18 15:59:24	INFO        Version 1.3.0.189      GameOverlay64 2116 VkRenderTest.exe - register_module - Register module for C:\WINDOWS\system32\dxgi.dll
	OCAT: 12/17/18 15:59:25	INFO        Version 1.3.0.189      GameOverlay64 2116 VkRenderTest.exe - register_module - Successfully installed hook for LoadLibraryA
	OCAT: 12/17/18 15:59:25	INFO        Version 1.3.0.189      GameOverlay64 2116 VkRenderTest.exe - register_module - Successfully installed hook for LoadLibraryExA
	OCAT: 12/17/18 15:59:25	INFO        Version 1.3.0.189      GameOverlay64 2116 VkRenderTest.exe - register_module - Successfully installed hook for LoadLibraryW
	OCAT: 12/17/18 15:59:25	INFO        Version 1.3.0.189      GameOverlay64 2116 VkRenderTest.exe - register_module - Successfully installed hook for LoadLibraryExW

**Comment by rys** [comment]
Could you share your VkRenderTest.exe binary by any chance, and are you using the launcher or the global overlay hook?

**Comment by Reedbeta** [comment]
Sure! Here's the binary & support files, in two versions with and without the validation layer. [VkRenderTest.zip](https://github.com/GPUOpen-Tools/OCAT/files/2688418/VkRenderTest.zip)

I'm using the global overlay hook. I just tried invoking through the "Launch App" tab in OCAT as well, and that gives me the "Failed to open dynamic library ... VK_LAYER_OCAT_overlay32.dll" error I mentioned earlier in this thread. That happens either with or without the validation layer.

**Comment by rys** [comment]
@Reedbeta great, we'll take a look and hopefully repro and have a fix soon!

**Comment by aurolou** [comment]
Thanks a lot for the sample!
Unfortunately, when I try to run it I get following error:

![image](https://user-images.githubusercontent.com/9432470/50145260-6fd1d400-02b1-11e9-8f1f-6a92dfd38ba8.png)

This happens with both versions and without OCAT attached. I am using VulkanSDK 1.1.92.1.

The "Failed to open dynamic library ... VK_LAYER_OCAT_overlay32.dll" error when launching the app through the "Launch APP" tab in OCAT should be fixed with this [version](https://ci.appveyor.com/api/buildjobs/gcp5vxcwtqbrnk2v/artifacts/OCAT_1.3.0.194.exe) 😊

**Comment by Reedbeta** [comment]
Thanks, and sorry about the error. Try [this one](https://github.com/GPUOpen-Tools/OCAT/files/2693421/VkRenderTest.zip), I've made some changes to descriptor pool sizes (seems NV's driver is not strict about these).

With 1.3.0.194 the "Launch App" tab works and I see the overlay, either with or without the validation layer! 🎉 But when launching through the global hook I still don't get the overlay showing up. I _sometimes_ see the stack overflow with the validation layer, other times the app launches (but no overlay); it's inconsistent.

**Comment by Reedbeta** [comment]
Thanks! Confirmed, in 1.3.0.195 the overlay shows up using the global hook, with no validation layer.

Unfortunately I still see a stack overflow when the validation layer is enabled. The top three stack frames are in the NV driver but then it looks like Vulkan and OCAT are calling each other in some kind of recursive loop.

```
vulkan-1.dll!vkGetDeviceProcAddr(VkDevice_T * device, const char * pName) Line 95
VK_LAYER_OCAT_overlay64.dll!00007ffa60b7b963()
vulkan-1.dll!vkGetDeviceProcAddr(VkDevice_T * device, const char * pName) Line 95
VK_LAYER_OCAT_overlay64.dll!00007ffa60b7b963()
vulkan-1.dll!vkGetDeviceProcAddr(VkDevice_T * device, const char * pName) Line 95
VK_LAYER_OCAT_overlay64.dll!00007ffa60b7b963()
...
```

These same two calls repeat some thousands of times. :( I've uploaded a minidump in case that's helpful: [VkRenderTest.dmp.zip](https://github.com/GPUOpen-Tools/OCAT/files/2701382/VkRenderTest.dmp.zip). This is on Vulkan SDK 1.1.92.1.

**Comment by aurolou** [comment]
Thanks for confirming!
I will look into the stack overflow next year - I still couldn't repro so at this point everything is more of a guess.

Do you have special layer settings on your system? E.g. some environment variables set?

**Comment by aurolou** [comment]
Just a quick update: I was able to reproduce the issue! Investigating now :)

**Comment by aurolou** [comment]
I know it took ages, but the fix for #68 should also solve this issue here (or see this [version](https://ci.appveyor.com/api/buildjobs/6myp6e1a56mn6egd/artifacts/OCAT_1.4.242.exe)).

**Comment by Reedbeta** [comment]
Awesome! I've confirmed 1.4.242 works with my app either with or without the validation layer. Thanks!
